### ISSUE TITLE
Invalid json Rpc response

### ISSUE THREAD

**Issue by rahulsonone1234** [Dnyaneshwari-Sonone/e-voting#1]
![Screenshot from 2020-07-11 21-29-20](https://user-images.githubusercontent.com/47055638/87228260-b15b3000-c3bd-11ea-8923-9f25fe5cb059.png)
![Screenshot from 2020-07-11 21-32-26](https://user-images.githubusercontent.com/47055638/87228318-0bf48c00-c3be-11ea-9505-09e323d9e262.png)

**Comment by rahulsonone1234** [comment]
Also in index.html, the linking is wrong 
it shows that CSS and js files are from the CSS and js folder but these folders do not exist

**Comment by Dnyaneshwari-Sonone** [comment]
Or you can find it on Sakshi Singh GitHub profile as of now.

**Comment by Dnyaneshwari-Sonone** [comment]
Hey
Might have missed something while uploading it to the GitHub . I don't have
files in my laptop those are in frnds laptop..Will let you know.

**Comment by rahulsonone1234** [comment]
Hi!✋
cool no problem !!!!✌
should I need to close the issue?

**Comment by Dnyaneshwari-Sonone** [comment]
Yes you can I will look into it. Thanks for letting me know.

**Comment by rahulsonone1234** [comment]
Your most welcome 🤝🔥🔥

**Comment by rahulsonone1234** [comment]
Issue was solved using a (#proxy server)

**Comment by Dnyaneshwari-Sonone** [comment]
Okay I haven't updated readme properly need to update it involving all the
steps for required environment setup.
Thanks.

**Comment by rahulsonone1234** [comment]
Okay just notify me when updated
Pleasure to have your active response 😊 tysm
